name: release

on:
    push:
        tags:
            - "v*"

jobs:
    publish:
        runs-on: ubuntu-latest
        environment: release
        container:
            image: mcr.microsoft.com/playwright:v1.58.2-noble
        permissions:
            id-token: write # Required for OIDC
            contents: write # required for zip release
        steps:
            # check out and build
            - uses: actions/checkout@v4
            - uses: ./.github/actions/build

            # publish to npm
            - name: publish to npm
              run: |
                npm -v
                npm publish

            # create and publish github release
            - name: install zip
              run: |
                apt-get update
                apt-get install -y zip
            - name: create archive
              run: |
                  zip -r release.zip \
                  dist/ \
                  examples/ \
                  README.md \
                  LICENSE \
            - name: github publish release
              uses: softprops/action-gh-release@v2
              with:
                  files: release.zip
                  tag_name: ${{ github.ref_name }}
                  name: ${{ github.ref_name }}