name: test

on:
    push:
        branches:
            - "**"
        # stop this running on all tagged releases
        # as it's already in the release workflow
        tags-ignore:
          - "**"

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: mcr.microsoft.com/playwright:v1.58.2-noble
        steps:
            # check out and build
            - uses: actions/checkout@v4
            - uses: ./.github/actions/build